### ISSUE TITLE
Add "reorganizing content" ideas into Writer's Toolkit

### ISSUE THREAD

**Issue by josmperez** [grafana/writers-toolkit#221] opened 2023-04-04 21:30 UTC
Summarize and transfer ideas from meeting notes held in March 2023 into Writer's Toolkit.

**Comment by osg-grafana** [comment] 2023-06-15 15:59
This issue is non-actionable without more context.

**Comment by josmperez** [comment] 2023-06-15 20:31
Sorry, I forgot tot add this link: https://docs.google.com/document/d/12DYQiNUjrkzB3NR26W4JF_31Sgadz9JlQTwdju5Y1m8/edit#heading=h.eh0y778urxgi

from our 3/27 meeting

**Comment by osg-grafana** [comment] 2023-06-16 11:14
This issue looks like a duplicate of https://github.com/grafana/technical-documentation/issues/613, and this work is intended to be performed by the Docs Team internally, so closing this in favor of `613`.

**Closed by osg-grafana** 2023-06-16 11:14 UTC
Labels: type/docs
